-- Project Name : noname
-- Date/Time    : 2024/10/12 17:01:43
-- Author       : nori
-- RDBMS Type   : Oracle Database
-- Application  : A5:SQL Mk-2

-- モンスターイメージマスタ
DROP TABLE M_MONSTER_IMG CASCADE CONSTRAINTS;

CREATE TABLE M_MONSTER_IMG (
  MONSTER_IMG_ID NUMBER NOT NULL
  , IMG_FILE_NAME VARCHAR2(100) NOT NULL
  , PIXEL_X NUMBER
  , PIXEL_Y NUMBER
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT M_MONSTER_IMG_PKC PRIMARY KEY (MONSTER_IMG_ID)
) ;

-- モンスターバトル詳細履歴
DROP TABLE T_MONSTER_BATTLE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE T_MONSTER_BATTLE_DETAIL (
  MONSTER_BATTLE_ID NUMBER NOT NULL
  , MONSTER_BATTLE_DETAIL NUMBER DEFAULT "ORACLE_USER"."ISEQ$$_75991".nextval
  , PLAYER_ID NUMBER NOT NULL
  , MONSTER_ID NUMBER NOT NULL
  , DAMAGE NUMBER
  , TURN_NUMBER NUMBER
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT T_MONSTER_BATTLE_DETAIL_PKC PRIMARY KEY (MONSTER_BATTLE_ID,MONSTER_BATTLE_DETAIL)
) ;

-- モンスターマスタ
DROP TABLE M_MONSTER CASCADE CONSTRAINTS;

CREATE TABLE M_MONSTER (
  MONSTER_ID NUMBER NOT NULL
  , PLAYER_ID NUMBER NOT NULL
  , MONSTER_TYPE_ID NUMBER NOT NULL
  , MONSTER_ATTRIBUTE_ID NUMBER NOT NULL
  , MONSTER_IMG_ID NUMBER NOT NULL
  , MONSTER_NAME VARCHAR2(100)
  , LV NUMBER DEFAULT 1
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT M_MONSTER_PKC PRIMARY KEY (MONSTER_ID)
) ;

-- モンスター属性マスタ
DROP TABLE M_MONSTER_ATTRIBUTE CASCADE CONSTRAINTS;

CREATE TABLE M_MONSTER_ATTRIBUTE (
  MONSTER_ATTRIBUTE_ID NUMBER NOT NULL
  , MONSTER_ATTRIBUTE_NAME VARCHAR2(50) NOT NULL
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT M_MONSTER_ATTRIBUTE_PKC PRIMARY KEY (MONSTER_ATTRIBUTE_ID)
) ;

-- モンスタータイプマスタ
DROP TABLE M_MONSTER_TYPE CASCADE CONSTRAINTS;

CREATE TABLE M_MONSTER_TYPE (
  MONSTER_TYPE_ID NUMBER NOT NULL
  , MONSTER_TYPE_NAME VARCHAR2(50) NOT NULL
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT M_MONSTER_TYPE_PKC PRIMARY KEY (MONSTER_TYPE_ID)
) ;

-- プレイヤーマスタ
DROP TABLE M_PLAYER CASCADE CONSTRAINTS;

CREATE TABLE M_PLAYER (
  PLAYER_ID NUMBER NOT NULL
  , PLAYER_NAME VARCHAR2(100) NOT NULL
  , LV NUMBER DEFAULT 1
  , EXPERIENCE NUMBER DEFAULT 0
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT M_PLAYER_PKC PRIMARY KEY (PLAYER_ID)
) ;

-- モンスターバトル履歴
DROP TABLE T_MONSTER_BATTLE CASCADE CONSTRAINTS;

CREATE TABLE T_MONSTER_BATTLE (
  MONSTER_BATTLE_ID NUMBER DEFAULT "ORACLE_USER"."ISEQ$$_75991".nextval NOT NULL
  , RESULT VARCHAR2(50) NOT NULL
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT T_MONSTER_BATTLE_PKC PRIMARY KEY (MONSTER_BATTLE_ID)
) ;

-- モンスター育成履歴
DROP TABLE T_MONSTER_GROWTH CASCADE CONSTRAINTS;

CREATE TABLE T_MONSTER_GROWTH (
  GROWTH_ID NUMBER DEFAULT "ORACLE_USER"."ISEQ$$_75988".nextval NOT NULL
  , MONSTER_ID NUMBER NOT NULL
  , GROWTH_TYPE VARCHAR2(50) NOT NULL
  , RESULT VARCHAR2(200) NOT NULL
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT T_MONSTER_GROWTH_PKC PRIMARY KEY (GROWTH_ID)
) ;

-- モンスター特訓履歴
DROP TABLE T_TRAINING_RECORD CASCADE CONSTRAINTS;

CREATE TABLE T_TRAINING_RECORD (
  TRAINING_ID NUMBER DEFAULT "ORACLE_USER"."ISEQ$$_75994".nextval NOT NULL
  , MONSTER_ID NUMBER NOT NULL
  , TRAINING_TYPE VARCHAR2(50) NOT NULL
  , RESULT VARCHAR2(200) NOT NULL
  , CREATED_BY VARCHAR2(100)
  , CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , UPDATED_BY VARCHAR2(100)
  , UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT T_TRAINING_RECORD_PKC PRIMARY KEY (TRAINING_ID)
) ;

COMMENT ON TABLE M_MONSTER_IMG IS 'モンスターイメージマスタ:モンスターのイメージを管理。';
COMMENT ON COLUMN M_MONSTER_IMG.MONSTER_IMG_ID IS 'モンスターイメージID';
COMMENT ON COLUMN M_MONSTER_IMG.IMG_FILE_NAME IS '画像ファイル名';
COMMENT ON COLUMN M_MONSTER_IMG.PIXEL_X IS '横位置(ピクセル)';
COMMENT ON COLUMN M_MONSTER_IMG.PIXEL_Y IS '縦位置(ピクセル)';
COMMENT ON COLUMN M_MONSTER_IMG.CREATED_BY IS '作成者';
COMMENT ON COLUMN M_MONSTER_IMG.CREATED_AT IS '作成日時';
COMMENT ON COLUMN M_MONSTER_IMG.UPDATED_BY IS '更新者';
COMMENT ON COLUMN M_MONSTER_IMG.UPDATED_AT IS '更新日時';

COMMENT ON TABLE T_MONSTER_BATTLE_DETAIL IS 'モンスターバトル詳細履歴:モンスター同士のバトル履歴を管理。バトル結果や参加モンスター情報を記録。';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.MONSTER_BATTLE_ID IS 'モンスターバトル履歴ID';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.MONSTER_BATTLE_DETAIL IS 'モンスターバトル履歴詳細ID';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.PLAYER_ID IS 'プレイヤーID';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.MONSTER_ID IS 'モンスターID';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.DAMAGE IS 'ダメージ:モンスターが与えたダメージ';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.TURN_NUMBER IS '行動のターン数:行動のターン数';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.CREATED_BY IS '作成者';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.CREATED_AT IS '作成日時';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.UPDATED_BY IS '更新者';
COMMENT ON COLUMN T_MONSTER_BATTLE_DETAIL.UPDATED_AT IS '更新日時';

COMMENT ON TABLE M_MONSTER IS 'モンスターマスタ:モンスターの基本情報を管理。プレイヤーID、タイプ、属性、レベルなど。';
COMMENT ON COLUMN M_MONSTER.MONSTER_ID IS 'モンスターID';
COMMENT ON COLUMN M_MONSTER.PLAYER_ID IS 'プレイヤーID';
COMMENT ON COLUMN M_MONSTER.MONSTER_TYPE_ID IS 'モンスタータイプID';
COMMENT ON COLUMN M_MONSTER.MONSTER_ATTRIBUTE_ID IS 'モンスター属性ID';
COMMENT ON COLUMN M_MONSTER.MONSTER_IMG_ID IS 'モンスターイメージID';
COMMENT ON COLUMN M_MONSTER.MONSTER_NAME IS 'モンスター名';
COMMENT ON COLUMN M_MONSTER.LV IS 'レベル';
COMMENT ON COLUMN M_MONSTER.CREATED_BY IS '作成者';
COMMENT ON COLUMN M_MONSTER.CREATED_AT IS '作成日時';
COMMENT ON COLUMN M_MONSTER.UPDATED_BY IS '更新者';
COMMENT ON COLUMN M_MONSTER.UPDATED_AT IS '更新日時';

COMMENT ON TABLE M_MONSTER_ATTRIBUTE IS 'モンスター属性マスタ:モンスターの属性を管理。';
COMMENT ON COLUMN M_MONSTER_ATTRIBUTE.MONSTER_ATTRIBUTE_ID IS 'モンスター属性ID';
COMMENT ON COLUMN M_MONSTER_ATTRIBUTE.MONSTER_ATTRIBUTE_NAME IS 'モンスター属性名';
COMMENT ON COLUMN M_MONSTER_ATTRIBUTE.CREATED_BY IS '作成者';
COMMENT ON COLUMN M_MONSTER_ATTRIBUTE.CREATED_AT IS '作成日時';
COMMENT ON COLUMN M_MONSTER_ATTRIBUTE.UPDATED_BY IS '更新者';
COMMENT ON COLUMN M_MONSTER_ATTRIBUTE.UPDATED_AT IS '更新日時';

COMMENT ON TABLE M_MONSTER_TYPE IS 'モンスタータイプマスタ:モンスターのタイプを管理。';
COMMENT ON COLUMN M_MONSTER_TYPE.MONSTER_TYPE_ID IS 'モンスタータイプID';
COMMENT ON COLUMN M_MONSTER_TYPE.MONSTER_TYPE_NAME IS 'モンスタータイプ名';
COMMENT ON COLUMN M_MONSTER_TYPE.CREATED_BY IS '作成者';
COMMENT ON COLUMN M_MONSTER_TYPE.CREATED_AT IS '作成日時';
COMMENT ON COLUMN M_MONSTER_TYPE.UPDATED_BY IS '更新者';
COMMENT ON COLUMN M_MONSTER_TYPE.UPDATED_AT IS '更新日時';

COMMENT ON TABLE M_PLAYER IS 'プレイヤーマスタ:プレイヤーの基本情報を管理。名前、レベル、経験値、所持モンスターなど。';
COMMENT ON COLUMN M_PLAYER.PLAYER_ID IS 'プレイヤーID';
COMMENT ON COLUMN M_PLAYER.PLAYER_NAME IS '名前';
COMMENT ON COLUMN M_PLAYER.LV IS 'レベル';
COMMENT ON COLUMN M_PLAYER.EXPERIENCE IS '経験値';
COMMENT ON COLUMN M_PLAYER.CREATED_BY IS '作成者';
COMMENT ON COLUMN M_PLAYER.CREATED_AT IS '作成日時';
COMMENT ON COLUMN M_PLAYER.UPDATED_BY IS '更新者';
COMMENT ON COLUMN M_PLAYER.UPDATED_AT IS '更新日時';

COMMENT ON TABLE T_MONSTER_BATTLE IS 'モンスターバトル履歴:モンスター同士のバトル履歴を管理。バトル結果や参加モンスター情報を記録。';
COMMENT ON COLUMN T_MONSTER_BATTLE.MONSTER_BATTLE_ID IS 'モンスターバトル履歴ID';
COMMENT ON COLUMN T_MONSTER_BATTLE.RESULT IS 'バトル結果';
COMMENT ON COLUMN T_MONSTER_BATTLE.CREATED_BY IS '作成者';
COMMENT ON COLUMN T_MONSTER_BATTLE.CREATED_AT IS '作成日時';
COMMENT ON COLUMN T_MONSTER_BATTLE.UPDATED_BY IS '更新者';
COMMENT ON COLUMN T_MONSTER_BATTLE.UPDATED_AT IS '更新日時';

COMMENT ON TABLE T_MONSTER_GROWTH IS 'モンスター育成履歴:モンスターの育成履歴を管理。育成タイプや結果を記録。';
COMMENT ON COLUMN T_MONSTER_GROWTH.GROWTH_ID IS '育成ID';
COMMENT ON COLUMN T_MONSTER_GROWTH.MONSTER_ID IS 'モンスターID';
COMMENT ON COLUMN T_MONSTER_GROWTH.GROWTH_TYPE IS '育成タイプ';
COMMENT ON COLUMN T_MONSTER_GROWTH.RESULT IS '結果';
COMMENT ON COLUMN T_MONSTER_GROWTH.CREATED_BY IS '作成者';
COMMENT ON COLUMN T_MONSTER_GROWTH.CREATED_AT IS '作成日時';
COMMENT ON COLUMN T_MONSTER_GROWTH.UPDATED_BY IS '更新者';
COMMENT ON COLUMN T_MONSTER_GROWTH.UPDATED_AT IS '更新日時';

COMMENT ON TABLE T_TRAINING_RECORD IS 'モンスター特訓履歴:モンスターの特訓履歴を管理。特訓タイプや結果を記録。';
COMMENT ON COLUMN T_TRAINING_RECORD.TRAINING_ID IS '特訓ID';
COMMENT ON COLUMN T_TRAINING_RECORD.MONSTER_ID IS 'モンスターID';
COMMENT ON COLUMN T_TRAINING_RECORD.TRAINING_TYPE IS '特訓タイプ';
COMMENT ON COLUMN T_TRAINING_RECORD.RESULT IS '結果';
COMMENT ON COLUMN T_TRAINING_RECORD.CREATED_BY IS '作成者';
COMMENT ON COLUMN T_TRAINING_RECORD.CREATED_AT IS '作成日時';
COMMENT ON COLUMN T_TRAINING_RECORD.UPDATED_BY IS '更新者';
COMMENT ON COLUMN T_TRAINING_RECORD.UPDATED_AT IS '更新日時';

