-- プレイヤーマスタの作成
CREATE TABLE m_player( 
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,         -- プレイヤーID
    name VARCHAR2(100) NOT NULL,                                         -- 名前
    lv NUMBER DEFAULT 1,                                                 -- レベル
    experience NUMBER DEFAULT 0,                                         -- 経験値
    created_by VARCHAR2(100),                                            -- 作成者
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                      -- 作成日時
    updated_by VARCHAR2(100),                                            -- 更新者
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                       -- 更新日時
); 

COMMENT ON TABLE m_player IS 'プレイヤーの基本情報を管理。名前、レベル、経験値、所持モンスターなど。'; 
COMMENT ON COLUMN m_player.player_id IS 'プレイヤーID'; 
COMMENT ON COLUMN m_player.name IS '名前'; 
COMMENT ON COLUMN m_player.lv IS 'レベル'; 
COMMENT ON COLUMN m_player.experience IS '経験値'; 
COMMENT ON COLUMN m_player.created_at IS '作成日時'; 
COMMENT ON COLUMN m_player.updated_at IS '更新日時'; 
COMMENT ON COLUMN m_player.created_by IS '作成者'; 
COMMENT ON COLUMN m_player.updated_by IS '更新者'; 

-- モンスターマスタの作成
CREATE TABLE m_monster (
    monster_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- モンスターID
    player_id NUMBER NOT NULL,                                          -- プレイヤーID
    monster_type_id NUMBER NOT NULL,                                   -- モンスタータイプID
    monster_attribute_id NUMBER NOT NULL,                              -- モンスター属性ID
    lv NUMBER DEFAULT 1,                                              -- レベルをlvに変更
    created_by VARCHAR2(100),                                          -- 作成者
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                    -- 作成日時
    updated_by VARCHAR2(100),                                          -- 更新者
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                     -- 更新日時
); 

COMMENT ON TABLE m_monster IS 'モンスターの基本情報を管理。プレイヤーID、タイプ、属性、レベルなど。'; 
COMMENT ON COLUMN m_monster.monster_id IS 'モンスターID'; 
COMMENT ON COLUMN m_monster.player_id IS 'プレイヤーID'; 
COMMENT ON COLUMN m_monster.monster_type_id IS 'モンスタータイプID'; 
COMMENT ON COLUMN m_monster.monster_attribute_id IS 'モンスター属性ID'; 
COMMENT ON COLUMN m_monster.lv IS 'レベル'; 
COMMENT ON COLUMN m_monster.created_at IS '作成日時'; 
COMMENT ON COLUMN m_monster.updated_at IS '更新日時'; 
COMMENT ON COLUMN m_monster.created_by IS '作成者'; 
COMMENT ON COLUMN m_monster.updated_by IS '更新者'; 

-- モンスタータイプマスタの作成
CREATE TABLE m_monster_type (
    type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,        -- タイプID
    type_name VARCHAR2(50) NOT NULL,                                   -- タイプ名
    created_by VARCHAR2(100),                                          -- 作成者
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                    -- 作成日時
    updated_by VARCHAR2(100),                                          -- 更新者
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                     -- 更新日時
);

COMMENT ON TABLE m_monster_type IS 'モンスターのタイプを管理。'; 
COMMENT ON COLUMN m_monster_type.type_id IS 'タイプID'; 
COMMENT ON COLUMN m_monster_type.type_name IS 'タイプ名'; 
COMMENT ON COLUMN m_monster_type.created_at IS '作成日時'; 
COMMENT ON COLUMN m_monster_type.updated_at IS '更新日時'; 
COMMENT ON COLUMN m_monster_type.created_by IS '作成者'; 
COMMENT ON COLUMN m_monster_type.updated_by IS '更新者'; 

-- モンスター属性マスタの作成
CREATE TABLE m_monster_attribute (
    attribute_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- 属性ID
    attribute_name VARCHAR2(50) NOT NULL,                             -- 属性名
    created_by VARCHAR2(100),                                          -- 作成者
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                    -- 作成日時
    updated_by VARCHAR2(100),                                          -- 更新者
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                     -- 更新日時
);

COMMENT ON TABLE m_monster_attribute IS 'モンスターの属性を管理。'; 
COMMENT ON COLUMN m_monster_attribute.attribute_id IS '属性ID'; 
COMMENT ON COLUMN m_monster_attribute.attribute_name IS '属性名'; 
COMMENT ON COLUMN m_monster_attribute.created_at IS '作成日時'; 
COMMENT ON COLUMN m_monster_attribute.updated_at IS '更新日時'; 
COMMENT ON COLUMN m_monster_attribute.created_by IS '作成者'; 
COMMENT ON COLUMN m_monster_attribute.updated_by IS '更新者'; 

-- モンスター育成記録の作成
CREATE TABLE t_monster_growth (
    growth_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- 育成ID
    monster_id NUMBER NOT NULL,                                        -- モンスターID
    growth_type VARCHAR2(50) NOT NULL,                               -- 育成タイプ
    result VARCHAR2(200) NOT NULL,                                   -- 結果
    created_by VARCHAR2(100),                                        -- 作成者
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                  -- 作成日時
    updated_by VARCHAR2(100),                                        -- 更新者
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- 更新日時
);

COMMENT ON TABLE t_monster_growth IS 'モンスターの育成履歴を管理。育成タイプや結果を記録。'; 
COMMENT ON COLUMN t_monster_growth.growth_id IS '育成ID'; 
COMMENT ON COLUMN t_monster_growth.monster_id IS 'モンスターID'; 
COMMENT ON COLUMN t_monster_growth.growth_type IS '育成タイプ'; 
COMMENT ON COLUMN t_monster_growth.result IS '結果'; 
COMMENT ON COLUMN t_monster_growth.created_at IS '作成日時'; 
COMMENT ON COLUMN t_monster_growth.updated_at IS '更新日時'; 
COMMENT ON COLUMN t_monster_growth.created_by IS '作成者'; 
COMMENT ON COLUMN t_monster_growth.updated_by IS '更新者'; 

-- モンスターバトル記録の作成
CREATE TABLE t_monster_battle (
    battle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- バトルID
    monster_id_1 NUMBER NOT NULL,                                    -- モンスター1 ID
    monster_id_2 NUMBER NOT NULL,                                    -- モンスター2 ID
    result VARCHAR2(50) NOT NULL,                                   -- バトル結果
    created_by VARCHAR2(100),                                       -- 作成者
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                 -- 作成日時
    updated_by VARCHAR2(100),                                       -- 更新者
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                  -- 更新日時
);

COMMENT ON TABLE t_monster_battle IS 'モンスター同士のバトル履歴を管理。バトル結果や参加モンスター情報を記録。'; 
COMMENT ON COLUMN t_monster_battle.battle_id IS 'バトルID'; 
COMMENT ON COLUMN t_monster_battle.monster_id_1 IS 'モンスター1 ID'; 
COMMENT ON COLUMN t_monster_battle.monster_id_2 IS 'モンスター2 ID'; 
COMMENT ON COLUMN t_monster_battle.result IS 'バトル結果'; 
COMMENT ON COLUMN t_monster_battle.created_at IS '作成日時'; 
COMMENT ON COLUMN t_monster_battle.updated_at IS '更新日時'; 
COMMENT ON COLUMN t_monster_battle.created_by IS '作成者'; 
COMMENT ON COLUMN t_monster_battle.updated_by IS '更新者'; 

-- 特訓記録の作成
CREATE TABLE t_training_record (
    training_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- 特訓ID
    monster_id NUMBER NOT NULL,                                        -- モンスターID
    training_type VARCHAR2(50) NOT NULL,                             -- 特訓タイプ
    result VARCHAR2(200) NOT NULL,                                   -- 結果
    created_by VARCHAR2(100),                                        -- 作成者
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                  -- 作成日時
    updated_by VARCHAR2(100),                                        -- 更新者
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                   -- 更新日時
);

COMMENT ON TABLE t_training_record IS 'モンスターの特訓履歴を管理。特訓タイプや結果を記録。'; 
COMMENT ON COLUMN t_training_record.training_id IS '特訓ID'; 
COMMENT ON COLUMN t_training_record.monster_id IS 'モンスターID'; 
COMMENT ON COLUMN t_training_record.training_type IS '特訓タイプ'; 
COMMENT ON COLUMN t_training_record.result IS '結果'; 
COMMENT ON COLUMN t_training_record.created_at IS '作成日時'; 
COMMENT ON COLUMN t_training_record.updated_at IS '更新日時'; 
COMMENT ON COLUMN t_training_record.created_by IS '作成者'; 
COMMENT ON COLUMN t_training_record.updated_by IS '更新者'; 

