-- モンスター属性マスタへのデータ挿入
INSERT INTO M_MONSTER_ATTRIBUTE (MONSTER_ATTRIBUTE_NAME, CREATED_BY) VALUES ('火', 'nori');
INSERT INTO M_MONSTER_ATTRIBUTE (MONSTER_ATTRIBUTE_NAME, CREATED_BY) VALUES ('水', 'nori');
INSERT INTO M_MONSTER_ATTRIBUTE (MONSTER_ATTRIBUTE_NAME, CREATED_BY) VALUES ('風', 'nori');
INSERT INTO M_MONSTER_ATTRIBUTE (MONSTER_ATTRIBUTE_NAME, CREATED_BY) VALUES ('土', 'nori');

-- モンスタータイプマスタへのデータ挿入
INSERT INTO M_MONSTER_TYPE (MONSTER_TYPE_NAME, CREATED_BY) VALUES ('ドラゴン', 'nori');
INSERT INTO M_MONSTER_TYPE (MONSTER_TYPE_NAME, CREATED_BY) VALUES ('獣', 'nori');
INSERT INTO M_MONSTER_TYPE (MONSTER_TYPE_NAME, CREATED_BY) VALUES ('鳥', 'nori');
INSERT INTO M_MONSTER_TYPE (MONSTER_TYPE_NAME, CREATED_BY) VALUES ('虫', 'nori');

-- プレイヤーマスタへのデータ挿入
INSERT INTO M_PLAYER (PLAYER_NAME, LV, EXPERIENCE, CREATED_BY) VALUES ('のり', 1, 0, 'nori');
INSERT INTO M_PLAYER (PLAYER_NAME, LV, EXPERIENCE, CREATED_BY) VALUES ('ひろき', 1, 0, 'nori');
INSERT INTO M_PLAYER (PLAYER_NAME, LV, EXPERIENCE, CREATED_BY) VALUES ('さき', 1, 0, 'nori');
INSERT INTO M_PLAYER (PLAYER_NAME, LV, EXPERIENCE, CREATED_BY) VALUES ('まさみ', 1, 0, 'nori');

-- モンスターマスタへのデータ挿入
INSERT INTO M_MONSTER (PLAYER_ID, MONSTER_TYPE_ID, MONSTER_ATTRIBUTE_ID, MONSTER_NAME, LV, CREATED_BY) VALUES (1, 1, 1, 'ファイアドラゴン', 5, 'nori');
INSERT INTO M_MONSTER (PLAYER_ID, MONSTER_TYPE_ID, MONSTER_ATTRIBUTE_ID, MONSTER_NAME, LV, CREATED_BY) VALUES (1, 2, 2, 'ウォーターリザード', 3, 'nori');
INSERT INTO M_MONSTER (PLAYER_ID, MONSTER_TYPE_ID, MONSTER_ATTRIBUTE_ID, MONSTER_NAME, LV, CREATED_BY) VALUES (2, 3, 3, 'ウィンドバード', 4, 'nori');
INSERT INTO M_MONSTER (PLAYER_ID, MONSTER_TYPE_ID, MONSTER_ATTRIBUTE_ID, MONSTER_NAME, LV, CREATED_BY) VALUES (2, 4, 4, 'アースビートル', 2, 'nori');


