spring:
  application:
    name: NoriMonsterGrow
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: oracle_user
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
