spring:
  application:
    name: NoriMonsterGrow
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: oracle_user
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  type-aliases-package: com.monstergrow.model
  mapper-locations: classpath:com/monstergrow/mapper/*.xml

